//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milestone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordering()
        {
            this.OrderingDetails = new HashSet<OrderingDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Order_state { get; set; }
        public string Order_time { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderingDetail> OrderingDetails { get; set; }
    }
}
