//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milestone
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderingDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Ordering_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
    
        public virtual Ordering Ordering { get; set; }
        public virtual Product Product { get; set; }
    }
}
